# Generated by Django 5.0 on 2026-06-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='auth_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
