# Generated by Django 5.0 on 2026-07-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_app', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('esewa', 'Esewa'), ('cod', 'Cash on Delivery')], default='esewa', max_length=20),
        ),
    ]
